### ISSUE TITLE
"sorry, don't know what to do with bcrypt"

### ISSUE THREAD

**Issue by ACPK** [aherve/pbkdf2-password-hasher#3]
When following the tutorial, I get the error:

    "sorry, don't know what to do with bcrypt"

**Comment by nharperc** [comment]
Is bcrypt installed on your system?

**Comment by ACPK** [comment]
@ACPK - Yes. The issue was that the tutorial I was following didn't include the step to remove the "bcrypt$" text from the users' encrpyted_passwords.
